[features]
seeds = false
skip-lint = false
[programs.devnet]
volatility = "2G33JvdE8AtTzpJ7viAYFMvPbg6zz5yRBMX5VPZ2K1uq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./wallet/id.json"

[test.validator]
url="https://api.devnet.solana.com"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
