[features]
seeds = false
skip-lint = false
[programs.localnet]
volatility = "FKLzkEN4iBf9dPFuxUjvVFZGtEqYXLZgdFn9hxa2sKKq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/rana/.config/solana/id.json"

[test.validator]
url="https://api.devnet.solana.com"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
